### ISSUE TITLE
How to test the model?

### ISSUE THREAD

**Issue by ZhengLeon** [DoubtedSteam/MPANet#1]
@DoubtedSteam 
Hi~
How can I eval the model and get the result in your paper after training?

Thanks!

**Comment by DoubtedSteam** [comment]
set epoch to 0 and resume the checkpoint
you can add the resume: path/to/the/checkpoint into yaml file

**Comment by ZhengLeon** [comment]
Thanks a lot!
If I enable the resume in training process, how can I update the epoch num instead of epoch0?

**Comment by DoubtedSteam** [comment]
edit num_epoch in yaml file

**Comment by DoubtedSteam** [comment]
edit num_epoch in yaml file

**Comment by ZhengLeon** [comment]
![image](https://user-images.githubusercontent.com/37479619/123390841-f5931080-d5cd-11eb-93cc-3804dce0ccf3.png)
Just edit the "num_epoch" in SYSU.yml doesn't work, isn't this "num_epoch" represent the max epoch?

**Comment by DoubtedSteam** [comment]
It is for max epoch
![image](https://user-images.githubusercontent.com/29891034/123391334-7f42de00-d5ce-11eb-8541-6f8a223eea5f.png)

**Comment by ZhengLeon** [comment]
In Chinese:
恢复训练时的epoch是从0开始的，这样似乎会覆盖之前的checkpoint,如何修改使重新训练的epoch是从resume的轮数开始呢？

**Comment by DoubtedSteam** [comment]
I didn't achieve this function.
You can add a start_epoch parameter for def get_trainer()  in engine/__init__.py

**Comment by ZhengLeon** [comment]
I see, thanks for you kind reply~
