### ISSUE TITLE
No such file or directory: './SYSU-MM01/exp/rand_perm_cam.mat'

### ISSUE THREAD

**Issue by Su-hya** [DoubtedSteam/MPANet#2]
![1](https://user-images.githubusercontent.com/57243743/123592538-e73c3300-d81f-11eb-9890-c7e38e169df6.png)
您好，我按照您的代码训练时，报了以下错误：
FileNotFoundError: [Errno 2] No such file or directory: './SYSU-MM01/exp/rand_perm_cam.mat'
SYSU-MM01数据集的exp文件夹下没有rand_perm_cam.mat文件，我该怎么办呢？

**Comment by DoubtedSteam** [comment]
请参考这个网址：
please ref this site
https://github.com/wuancong/SYSU-MM01/tree/master/evaluation/data_split

**Comment by Su-hya** [comment]
好的，谢谢！

**Comment by wangxianjv** [comment]
I can not download rand_perm_cam.mat,can you send it to my emali(wangxianjv@qq.com),Thank you!
